### ISSUE TITLE
Can't Enable Theme

### ISSUE THREAD

**Issue by jonleopard** [dracula/telegram#11]
Perhaps I'm missing something in the instructions, but I cannot figure out how to apply this theme in the macOS edition of Telegram.

I'm looking inside 
Preferences > Theme, and don't see anywhere that indicates adding a custom theme.

Thanks!

**Comment by blocksninja** [comment]
Same here. After clicking "Chat Background" I can click "Custom Background", but that only will allow me to select an image file, not the template file.

**Comment by nmsmith22389** [comment]
There are two different versions of Telegram available for macOS.

### Telegram
- The *native* macOS version.
- Has native design.
- Supports secret chats.
- **Does not support custom themes.**

### Telegram Desktop
- The macOS version of the multi-platform version of Telegram.
- **Supports custom themes.**

You can only use custom themes with the version titled `Telegram Desktop` *(found in the app store)*.

Here is a picture of where the option is located in `Telegram Desktop`.
<img width="400" alt="telegramthemehowto" src="https://user-images.githubusercontent.com/8648114/41892303-2b7fca04-78dd-11e8-999f-ecb79c129065.png">

**Comment by jonleopard** [comment]
Thank you @nmsmith22389 for clearing that up! I was able to install the other version and activate the theme :)
