### ISSUE TITLE
Doesn't work on Telegram for MacOS

### ISSUE THREAD

**Issue by pablohs1986** [dracula/telegram#19]
Doesn't work on Telegram for MacOS. The file has a **tdesktop-theme** extension, however the current version of Telegram for MacOS needs a **.palette** file extension to be imported.

Could you review it? Since this version of the theme works perfectly for Telegram on Windows, a good idea would be to generate a new version exclusively for MacOS :)

**Comment by ryandevz** [comment]
@pablohs1986 are you trying apply theme for "Telegram Lite" version? There two version of client where cross platform one called "Telegram Lite" and "Telegram" which is native written on Swift.

![photo_2020-04-01_03-53-29](https://user-images.githubusercontent.com/32381359/95962934-e2cc0900-0dbb-11eb-8e8e-6d782b48d11d.jpg)

**Comment by pablohs1986** [comment]
I have tested on Telegram Lite and it works. It would be convenient that you specify it in the documentation, to avoid misunderstandings.

Thank you!!!
