### ISSUE TITLE
background not change in telegram 2.4.7

### ISSUE THREAD

**Issue by zdmgmail** [dracula/telegram#20]
![11-18_10:11:09](https://user-images.githubusercontent.com/50515839/99473922-9067a480-2986-11eb-843d-96a1e58b0e50.png)
![11-18_10:10:12](https://user-images.githubusercontent.com/50515839/99473927-93629500-2986-11eb-963e-02f574466eed.png)
![11-18_10:15:38](https://user-images.githubusercontent.com/50515839/99474180-14219100-2987-11eb-9b49-c4b9e556a972.png)

**Comment by mitchschaft** [comment]
I just ran into this. If you go to the release page and download 'dracula-theme.tdesktop-theme' and install that instead it works normal. Took me 30 minutes to figure that out. 
https://github.com/dracula/telegram/releases/tag/v0.1.2

**Comment by zdmgmail** [comment]
> I just ran into this. If you go to the release page and download 'dracula-theme.tdesktop-theme' and install that instead, it works normal without that goofy flower background. Took me 30 minutes to figure that out.
> https://github.com/dracula/telegram/releases/tag/v0.1.2

Thanks, solved . Don't know why not same as `git clone ...`
