### ISSUE TITLE
Transfer done!

### ISSUE THREAD

**Issue by nmsmith22389** [dracula/telegram#5]
Hey @mazipan I've got everything transferred over finally! If you could look it over and let me know how it looks that would be great. Anything you see that needs to be added or changed either open an issue and I'll get to it or a PR if you want to change it. Later on I'll post a "Best Practices" guide on how to treat the branches and everything but mainly its just using Git Flow so all the work is done on the `develop` branch and when everything is ready for a new version its opened in a `release` branch then merged into `master` and back to `develop`. That sounds complicated but you can just open a PR and I'll make sure it's on the right branch and everything before merging.

The only thing that's not really finished are the *`intro` (first app run?)*  variables. I've opened an issue for it here #4. Also, I'm for the most part a macOS user so I haven't fully tested out a lot of the Windows variables. So if you use Windows let me know if anything looks off.

Thanks!

PS I'll also let @zenorocha know it's transferred over and that I'll do the codepen one next.

**Comment by zenorocha** [comment]
Awesooome! Can I add it to the website?

**Comment by nmsmith22389** [comment]
Sure! Go ahead! Maybe just give it a once over to make sure nothing needs to be changed. I did see your thing about the changelog so I'll get rid of the file. I was using both the file and releases so I shouldn't need to add anything.

**Comment by zenorocha** [comment]
Just added the page on draculatheme.com: https://github.com/dracula/dracula.github.io/commit/4e21d987f20df92abac6034901627dee56b38427

And made some changes here based on that: https://github.com/dracula/telegram/commit/a66a13d2946e0dfb389f7c5b9c76816435cdd778

Let me know if you would like to change anything: https://draculatheme.com/telegram

**Comment by nmsmith22389** [comment]
Thanks for updating the README! I'll let you know if I notice anything.
