### ISSUE TITLE
Move CHANGELOG to GitHub Releases

### ISSUE THREAD

**Issue by zenorocha** [dracula/telegram#6]
Hey @nmsmith22389, all other repositories use GitHub Releases for changelogs (https://github.com/dracula/visual-studio-code/releases). Would you mind following that pattern too?

**Comment by nmsmith22389** [comment]
I did check out the repo you sent me and they appear to be using both releases and the `CHANGELOG.md` file which is the same way I have it. Did you want me to delete the file or can I just use both like they do in the VSCode theme?

**Comment by zenorocha** [comment]
Ohh, I didn't see that, it should be removed from there as well.

**Comment by nmsmith22389** [comment]
Ok I'll delete the file then. Thanks!

**Comment by zenorocha** [comment]
Thanks!

What do you think of adding this changelog section to every repository?
