### ISSUE TITLE
Some names in chat has color of background

### ISSUE THREAD

**Issue by lamartire** [dracula/telegram#7]
It makes names invisible:

![image](https://user-images.githubusercontent.com/13414205/27394445-d39698a4-56b4-11e7-9caa-24ed49cc08ce.png)
#
This is message with reply. Name is invisible.

**Comment by FlorianLoch** [comment]
I am having the same problem, very confusing - I guess slightly changing the color of the bubble would be the way to go or can one also influence the color taken for the names in group conversations?
